/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/magic_book.glb -o src/components/Notebook.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/magic_book.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.MeshSG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert5SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/magic_book.glb')
